valid_users = {
    "lsilveira": {"password": "senha123", "profile": 3},
    #"lamaral": {"password": "lamaral23", "profile": 1},
    "blamim": {"password": "lamim23", "profile": 3},
    "mrodrigues": {"password": "mrodrigues23", "profile": 3},
    "alexbadcarrel": {"password": "Badminton76", "profile": 3},
    "Ellwanger": {"password": "21ellwanger", "profile": 3}, 
    "bulquinha": {"password": "evrr1111", "profile": 1}, 
    "rafaelmax": {"password": "19cYqCqu!OpO", "profile": 1}, 
    "Eanes": {"password": "Eanes@Analysis", "profile": 2}, 
    "wagnercw": {"password": "G28M1V97@", "profile": 1}, 
    "bjales": {"password": "kisso1cc", "profile": 3}, 
    "DANIELSANTOS": {"password": "140751@Ju", "profile": 3},
    "estevaobayerl": {"password": "Test2320", "profile": 3},
    "Alison": {"password": "040712aJ@19", "profile": 3},
    "GustavoMartins": {"password": "1985", "profile": 2}, 
    "douglasgornimello": {"password": "feliz@!2023", "profile": 1}, 
    "fabiofs": {"password": "030791", "profile": 1},
    "gugafdk": {"password": "Gui280419#", "profile": 3},
    "wagner2662": {"password": "flamengo26624364", "profile": 3},
    #"mmoren0": {"password": "mmoren23", "profile": 3}, 
    "willame_eduardo": {"password": "Will2015", "profile": 3},
    "santanabet85": {"password": "santana85", "profile": 3},
    "fagnerom": {"password": "120714", "profile": 3},
    "Mayconjp19": {"password": "210319", "profile": 3},
    "Edward": {"password": "Edward23", "profile": 3},
    "suporteacampo": {"password": "analise2023", "profile": 3}, 
    "bhctorres1982": {"password": "Rafael2015*", "profile": 3},
    "Felipe Gonçalves": {"password": "felipesantos", "profile": 3},
    "Borguezam": {"password": "91579877Luiz.", "profile": 1},
    "Romeu": {"password": "301510", "profile": 2},
    "thomasgabriel": {"password": "thomas123", "profile": 1} 
}
